export default  {
    products:[
        {
            _id: '123',
            productName: "my Product hello ",
            productDesc: "product desc",
            productDisplayDesc: "product desc",
            productCamDesc: "product desc",
            productBatteryDesc: "product desc",
            productPrice: "40000",
            productImage: "/images/product/Huawei-Nova-3.jpg",
            visitLink:"www.google.com",
            color:["blue","White","Green"],
            storage:[64,32,16,8],
            relatedImg:["/images/product/Huawei-Nova-3.jpg","/images/product/Huawei-Nova-3.jpg","/images/product/Huawei-Nova-3.jpg"],
        },
        {
            _id: '124',
            productName: "my Product 2",
            productDesc: "product desc",
            productDisplayDesc: "product desc",
            productCamDesc: "product desc",
            productBatteryDesc: "product desc",
            productPrice: "40000",
            productImage: "images/product/Huawei y5.jpg",
            visitLink:"www.google.com",
            color:["blue","White","Green"],
            storage:[64,32,16,8],
            relatedImg:["/images/product/Huawei-Nova-3.jpg","/images/product/Huawei-Nova-3.jpg","/images/product/Huawei-Nova-3.jpg"],
        },
        {
            _id: '125',
            productName: "my Product",
            productDesc: "product desc",
            productDisplayDesc: "product desc",
            productCamDesc: "product desc",
            productBatteryDesc: "product desc",
            productPrice: "40000",
            productImage: "/images/product/iphone 11pro.jpg",
            visitLink:"www.google.com",
            color:["blue","White","Green"],
            storage:[64,32,16,8],
            relatedImg:["/images/product/Huawei-Nova-3.jpg","/images/product/Huawei-Nova-3.jpg","/images/product/Huawei-Nova-3.jpg"],
        },
    ]
}